schemaVersion: 2.0
timeout: 30

notify:
  pullRequestComment:
    postOnSuccess: false

machine:
  java:
    version: 1.8
  env:
    skipTest: false

publish:
  reports:
    checkstyle: true
    pmd: true
    findbugs: true
    junit: true

pipelines:
# master builds
- branchName: pie-poc
  build:
    template: buildozer:v1:prb

# --------------------------
# Publish pipelines
- branchName: pie-poc
  build:
    template: buildozer:v1:publish
  publish:
    libraries: true
  finally:
    radar:
      annotate: true


